language: java

before_install:
  - wget https://services.gradle.org/distributions/gradle-6.1-bin.zip
  - unzip -qq gradle-6.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v